### ISSUE TITLE
Tree Borrows violation due to copied `&mut`

### ISSUE THREAD

**Issue by icmccorm** [aloucks/spng-rs#11]
I've been experimenting with [MiriLLI](https://github.com/icmccorm/mirilli): a version of Miri that can execute foreign function calls. It found an aliasing violation under Tree Borrows in the test case `decode`. Tree Borrows is still experimental, so this isn't an immediate security issue, but it should be fixed to avoid unsound optimizations in the future. 
```
error: Undefined Behavior: reborrow through <176464> at alloc61166[0x0] is forbidden
   --> /spng/src/lib.rs:345:13
    |
345 |             ctx,
    |             ^^^ reborrow through <176464> at alloc61166[0x0] is forbidden
    |
    = help: this indicates a potential bug in the program: it performed an invalid operation, but the Tree Borrows rules it violated are still experimental
    = help: the accessed tag <176464> is a child of the conflicting tag <176461>
    = help: the conflicting tag <176461> has state Disabled which forbids this reborrow (acting as a child read access)
help: the accessed tag <176464> was created here
   --> /spng/src/raw.rs:481:23
    |
481 |         self.reader = Some(boxed);
    |                       ^^^^^^^^^^^
help: the conflicting tag <176461> was created here, in the initial state Reserved
   --> /spng/src/raw.rs:481:28
    |
481 |         self.reader = Some(boxed);
    |                            ^^^^^
help: the conflicting tag <176461> later transitioned to Disabled due to a foreign write access at offsets [0x0..0x10]
   --> /spng/src/raw.rs:24:19
    |
24  |         let ret = reader.read(buf);
    |                   ^^^^^^^^^^^^^^^^
    = help: this transition corresponds to a loss of read and write permissions
```
It seems like this is due to the following pattern used in the function `set_png_stream` in [src/raw.rs](https://github.com/aloucks/spng-rs/blob/master/spng/src/raw.rs):
```
let mut boxed = Box::new(reader);
let user = boxed.as_mut() as *mut R as *mut _;
self.reader = Some(boxed);
...
unsafe { check_err(sys::spng_set_png_stream(self.raw, read_fn, user)) }
```
The pointer `user` is derived from the mutable borrow created by `boxed.as_mut()`, and it asserts unique access to the memory location. However, it is copied into the foreign heap within the body of the function `spng_set_png_stream`:
```
int spng_set_png_stream(spng_ctx *ctx, spng_read_fn *read_func, void *user)
{
    ...
    ctx->read_user_ptr = user;
```
Meanwhile, `self.reader` also asserts unique access to the location. When either of these references is used to write to memory, the other one will be invalidated. In this case, the FFI mutates through `read_user_ptr` first in the body of `read_fn`, causing `self.reader` to be invalid.

We can fix this by "unwrapping" the `Box<R>` within the body of `set_png_stream`.

**Comment by aloucks** [comment]
Thanks and sorry for the delay!
